### ISSUE TITLE
doesnt work install

### ISSUE THREAD

**Issue by LexterS999** [WaaromZoMoeilijk/TSP-DNS-fix#1]
I try to install on Debian 9/10/11 and Ubuntu 18/20.4 on my abroad VPS and installation doesn't work at all. It doesn't end successfully anytime and error with dkping and unbond restart all the time

**Comment by LexterS999** [comment]
Please optimize it for Ubuntu 18/20 and Debian 10/11

**Comment by WaaromZoMoeilijk** [comment]
No support is given. This is intended for RaspberryPI OS and has custom requirements for a client.
